export const NEST_CATEGORIES_CACHE_KEY = "NEST_CATEGORIES_CACHE_KEY";
export const LUNAR_CATEGORIES_CACHE_KEY = "LUNAR_CATEGORIES_CACHE_KEY";

// Conquest
export const CONQUEST_CATEGORIES_CACHE_KEY = "CONQUEST_CATEGORIES_CACHE_KEY";

//
export const IS_PERSIST_NAME = "persist";
